name = "hagerstenstreetcut"
description = "The best barbershop in the south of Stockholm."

[project]
id = 2
name = "hagerstenstreetcut"
repository = "hagerstenstreetcut"
description = "hejhejhej"
created_at = "2025-05-29T16:10:57.481Z"
updated_at = "2025-05-29T16:10:57.481Z"
